development:
  forest_env_secret: 7ec5206436ab99cd854201b45a8b88b149d8d2c3d37ef7c8dbfacf912bd58169
  forest_auth_secret: 9o61oP3_wjwNgdTtHPI8GQ
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
