development:
  forest_env_secret: 7ec5206436ab99cd854201b45a8b88b149d8d2c3d37ef7c8dbfacf912bd58169
  forest_auth_secret: 9o61oP3_wjwNgdTtHPI8GQ
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>

FOREST_ENV_SECRET: 088dccb7e12e5aa4d81a2ecec9adf49bd15c8dad497ad68e2d2d62bc4f0128d1
FOREST_AUTH_SECRET: 31aeb0b9625f3d2965b1c93a8c392a6d5974cc5b594feda9
FOREST_APPLICATION_URL: https://olivia-and-tom.herokuapp.com
